language: python

python:
 - "3.5"
 - "3.6"
 - "3.6-dev"
 - "3.7-dev"
 - "nightly"
 - "pypy3"

services:
 - redis-server

install:
 - pip install -r requirements.txt -r requirements-test.txt
 - pip install coveralls

before_script:
  - psql -c 'create database mygpo_test;' -U postgres

script:
  - pytest --cov=mygpo/ --cov-branch

after_script:
  - coveralls

env:
 - DATABASE_URL="postgres://postgres@localhost/mygpo_test"

sudo: false
